### ISSUE TITLE
<a> .stb-btn changes text color after becoming visited

### ISSUE THREAD

**Issue by anastasiagryshchenko** [storebrand/storebrand.ny#29] opened 2015-10-07 13:56 UTC
As this is a button, shouldn't it remain the white text color (for usual text color)?
Fixed inside the solution, but it could be nice to have it in the initial css.

after being "visited" button starts to look like this:
![image](https://cloud.githubusercontent.com/assets/8438849/10339472/c4ff6684-6d0b-11e5-9683-84935d15bd19.png)

  a:visited.stb-btn {
    color: #fff;
  }

**Comment by nilsel** [comment] 2016-01-06 16:16
This is reproduced here with 0.88 version: https://jsfiddle.net/nilsel/jdqw8db2/
Weirdly I cannot reproduce it in the web manual using devtools. Testing out a fix now.

**Comment by nilsel** [comment] 2016-01-06 16:27
Fix has been comitted to master, closing.

**Closed** 2016-01-06 16:27 UTC
Labels: bug
